
resource "aws_s3_bucket" "s3_bucket" {
  bucket = var.aws_s3_bucket_bucket
  acl    = var.aws_s3_bucket_acl

  tags = merge(
    {
      # unfortunately we cannot use the self keyword here
      # to retrieve the autogenerated name
      "Name" = format("%s", var.aws_s3_bucket_name)
    },
    var.tags,
    var.aws_s3_bucket_tags,
  )
}

